version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - run:
          name: Debug
          command: ls -la

      - run:
          working_directory: ~/functions
          name: Install Dependencies
          command: npm install

      - run:
          working_directory: ~/functions
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_TOKEN"

notify:
  webhooks:
    - url: https://us-central1-ci-dashboard-db276.cloudfunctions.net/dashboard/

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
