version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - restore_cache:
          working_directory: ~/project/functions
          name: Restore Npm Package Cache
          keys:
            - functions-packages-{{ checksum "package-lock.json" }}

      - run:
          working_directory: ~/project/functions
          name: Install Dependencies
          command: npm install

      - save_cache:
          working_directory: ~/project/functions
          name: Save Npm Package Cache
          key: functions-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - run:
          working_directory: ~/project/functions
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_TOKEN"

      - restore_cache:
          working_directory: ~/project/app
          name: Restore Npm Package Cache
          keys:
            - app-packages-{{ checksum "package-lock.json" }}

      - run:
          working_directory: ~/project/app
          name: Install app deps
          command: npm install

      - save_cache:
          working_directory: ~/project/app
          name: Save Npm Package Cache
          key: app-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - run:
          working_directory: ~/project/app
          name: Build app
          command: npm run build

      - run:
          working_directory: ~/project
          name: Deploy
          command: ./functions/node_modules/.bin/firebase deploy --only hosting --token "$FIREBASE_TOKEN"

notify:
  webhooks:
    - url: https://us-central1-ci-dashboard-db276.cloudfunctions.net/dashboard/

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
